import { Sun, Home, Droplets, Wheat, Zap, Building2, Battery, Atom, Wrench, FileCheck } from 'lucide-react';

export const PRODUCTS_DATA = [
  {
    id: 'ground-mounted-solar',
    title: 'Ground Mounted Solar Power Plants',
    slug: 'ground-mounted-solar',
    category: 'EPC Services',
    description: 'Large-scale solar installations on open land, designed for maximum energy output. Ideal for industrial zones, agricultural land, and KUSUM scheme projects.',
    image_url: 'https://images.unsplash.com/photo-1509391366360-2e959784a276?w=800&q=80&auto=format&fit=crop',
    icon: Sun,
    specs: '50 KW \u2013 20 MW+ | On-Grid / Off-Grid',
    features: [
      'End-to-end EPC: Survey \u2192 Design \u2192 Procurement \u2192 Commissioning',
      'Government approvals and liaisoning handled',
      'O&M post-commissioning included',
      'KUSUM-A, KUSUM-B, KUSUM-C scheme eligible',
    ],
    is_published: true,
  },
  {
    id: 'rooftop-solar',
    title: 'Rooftop Solar Power Plants',
    slug: 'rooftop-solar',
    category: 'EPC Services',
    description: 'Convert unused roof space into a power-generating asset. Custom designs for homes, offices, factories, hospitals, and universities.',
    image_url: 'https://images.unsplash.com/photo-1558449028-b53a39d100fc?w=800&q=80&auto=format&fit=crop',
    icon: Home,
    specs: '1 KW \u2013 500 KW+ | On-Grid / Off-Grid / Hybrid',
    features: [
      'Custom system design for every roof type',
      'Waaree panels \u2014 authorized partner',
      'Net metering registration handled',
      'Real-time monitoring and tracking',
    ],
    is_published: true,
  },
  {
    id: 'floating-solar',
    title: 'Floating Solar Power Plants',
    slug: 'floating-solar',
    category: 'EPC Services',
    description: 'Solar panels on floating HDPE structures over reservoirs, lakes, and irrigation tanks. Combines clean energy with water conservation.',
    image_url: 'https://images.unsplash.com/photo-1613665813446-82a78c468a1d?w=800&q=80&auto=format&fit=crop',
    icon: Droplets,
    specs: '100 KW \u2013 10 MW+ | HDPE Floating Structures',
    features: [
      'Custom-engineered floating pontoon systems',
      'Mooring and anchoring for stability',
      '10-15% higher efficiency (cooler environment)',
      'Reduces water evaporation by up to 70%',
    ],
    is_published: true,
  },
  {
    id: 'agrovoltaic-systems',
    title: 'Agrovoltaic Systems',
    slug: 'agrovoltaic-systems',
    category: 'EPC Services',
    description: 'Dual-use systems for simultaneous solar energy generation and crop cultivation under elevated solar panels. Farm + power in one setup.',
    image_url: 'https://images.unsplash.com/photo-1625246333195-78d9c38ad449?w=800&q=80&auto=format&fit=crop',
    icon: Wheat,
    specs: '500 KW \u2013 5 MW+ | Elevated MMS (2.5m\u20134m)',
    features: [
      'Custom elevated Module Mounting Structure',
      'Crop yield guidance and agronomy advisory',
      'Integration with irrigation systems',
      'KUSUM scheme subsidy assistance',
    ],
    is_published: true,
  },
  {
    id: 'transmission-lines',
    title: 'Transmission Lines (EHT & HT)',
    slug: 'transmission-lines',
    category: 'EPC Services',
    description: 'Construction of Extra High Tension and High Tension transmission lines for power evacuation and grid connectivity. Up to 765 KV.',
    image_url: 'https://images.unsplash.com/photo-1473341304170-971dccb5ac1e?w=800&q=80&auto=format&fit=crop',
    icon: Zap,
    specs: '33 KV \u2013 765 KV | Plains, Hilly, Forest terrain',
    features: [
      'Topographic survey and route optimization',
      'Tower design and civil foundation work',
      'Conductor stringing and hardware fitting',
      'Experience in hilly terrain of Madhya Pradesh',
    ],
    is_published: true,
  },
  {
    id: 'substations',
    title: 'Substations (GIS & AIS)',
    slug: 'substations',
    category: 'EPC Services',
    description: 'High-voltage substations including Gas Insulated (GIS) and Air Insulated (AIS) types, plus 132KV traction substations for Indian Railways.',
    image_url: 'https://images.unsplash.com/photo-1548337138-e87d889cc369?w=800&q=80&auto=format&fit=crop',
    icon: Building2,
    specs: '33 KV \u2013 400 KV | Design to Commissioning',
    features: [
      'Civil work and building construction',
      'Equipment supply and erection',
      'Protection and control panel installation',
      'Railway traction substation specialization',
    ],
    is_published: true,
  },
  {
    id: 'bess',
    title: 'BESS \u2014 Battery Energy Storage',
    slug: 'bess',
    category: 'Energy Storage',
    description: 'Advanced battery systems that store surplus solar energy for grid stabilization, peak shaving, and backup power during outages.',
    image_url: 'https://images.unsplash.com/photo-1620714223084-8fcacc6dfd8d?w=800&q=80&auto=format&fit=crop',
    icon: Battery,
    specs: 'Li-ion / LFP | Industrial, Commercial, Utility-scale',
    features: [
      'Grid stabilization capability',
      'Peak shaving and load shifting',
      'Backup power during outages',
      'Remote monitoring with BMS integration',
    ],
    is_published: true,
  },
  {
    id: 'green-hydrogen',
    title: 'Green Hydrogen',
    slug: 'green-hydrogen',
    category: 'Future Energy',
    description: 'Zero-emission hydrogen produced via solar-powered electrolysis. Clean fuel for industry, transport, and long-duration energy storage.',
    image_url: 'https://images.unsplash.com/photo-1532601224476-15c79f2f7a51?w=800&q=80&auto=format&fit=crop',
    icon: Atom,
    specs: 'Solar Electrolysis | Zero Carbon Output',
    features: [
      'Zero carbon emissions end-to-end',
      'Alternative to fossil fuels for industry',
      'Long-duration energy storage capability',
      'Suitable for hard-to-decarbonize sectors',
    ],
    is_published: true,
  },
  {
    id: 'asset-management',
    title: 'Asset Management & O&M',
    slug: 'asset-management',
    category: 'Support Services',
    description: 'Comprehensive operation, maintenance, and real-time SCADA performance monitoring for solar plants and power infrastructure assets.',
    image_url: 'https://images.unsplash.com/photo-1581092918056-0c4c3acd3789?w=800&q=80&auto=format&fit=crop',
    icon: Wrench,
    specs: 'Solar PV | Transmission | Substations',
    features: [
      'Preventive and corrective maintenance',
      'Energy audits and performance benchmarking',
      'Fault detection and rapid response',
      'Monthly performance reporting',
    ],
    is_published: true,
  },
  {
    id: 'approvals-liaisoning',
    title: 'Approvals & Liaisoning',
    slug: 'approvals-liaisoning',
    category: 'Support Services',
    description: 'End-to-end management of government permits, regulatory clearances, and liaisoning for solar and power infrastructure projects.',
    image_url: 'https://images.unsplash.com/photo-1450101499163-c8848c66ca85?w=800&q=80&auto=format&fit=crop',
    icon: FileCheck,
    specs: 'DISCOM | MNRE | State Nodal Agency | KUSUM',
    features: [
      'Application filing and follow-up',
      'Coordination with MPPTCL, MPPKVVCL, MPPMCL',
      'Net metering and subsidy disbursement',
      'Expert knowledge of MP state regulations',
    ],
    is_published: true,
  },
];

export const PRODUCT_CATEGORIES = ['All', 'EPC Services', 'Energy Storage', 'Future Energy', 'Support Services'];
