export const FEATURED_PROJECTS = [
  {
    id: 'guna-20mw',
    title: '20 MW Ground Mounted Solar',
    capacity: '20 MW',
    location: 'Guna, MP',
    year: 'Ongoing',
    type: 'Solar EPC',
    tag: 'Flagship Project',
    description: 'Open Access ground-mounted solar power plant \u2014 one of the largest in the region.',
    image_url: 'https://images.unsplash.com/photo-1508514177221-188b1cf16e9d?w=800&q=80&auto=format&fit=crop',
  },
  {
    id: '765kv-nokha',
    title: '765 KV Transmission Line',
    capacity: '765 KV',
    location: 'Nokha, Rajasthan',
    year: '2024',
    type: 'Transmission',
    tag: 'Highest Voltage',
    description: 'Extra High Tension transmission line executed for L&T Construction / PGCIL.',
    image_url: 'https://images.unsplash.com/photo-1473341304170-971dccb5ac1e?w=800&q=80&auto=format&fit=crop',
  },
  {
    id: '132kv-balaghat',
    title: '132 KV Traction Substation',
    capacity: '132 KV',
    location: 'Balaghat, MP',
    year: '2020',
    type: 'Substation',
    tag: 'Indian Railways',
    description: 'Railway traction substation for KEC International / Indian Railways.',
    image_url: 'https://images.unsplash.com/photo-1548337138-e87d889cc369?w=800&q=80&auto=format&fit=crop',
  },
  {
    id: 'bhopal-airport-1mw',
    title: '1 MW Solar Power Plant',
    capacity: '1 MW',
    location: 'Bhopal Airport',
    year: '2018',
    type: 'Solar EPC',
    tag: 'Landmark',
    description: 'Ground mounted solar installation at Bhopal Airport.',
    image_url: 'https://images.unsplash.com/photo-1558449028-b53a39d100fc?w=800&q=80&auto=format&fit=crop',
  },
  {
    id: 'drdo-delhi-200kw',
    title: '200 KW Rooftop Solar \u2014 DRDO',
    capacity: '200 KW',
    location: 'Delhi',
    year: '2024',
    type: 'Solar EPC',
    tag: 'Defence Sector',
    description: 'Rooftop solar for DRDO Mayur Bihar complex, New Delhi.',
    image_url: 'https://images.unsplash.com/photo-1509391366360-2e959784a276?w=800&q=80&auto=format&fit=crop',
  },
];

export const ONGOING_PROJECTS = [
  { title: '3 MW Ground Mounted On-Grid EPC \u2014 Rajlaxami Dev Build India Pvt Ltd', capacity: '3000 KW', location: 'Hazaratpur Awan, Dist. Guna', year: 'Ongoing' },
  { title: '2 MW Ground Mounted On-Grid EPC \u2014 Bharti Raikwar', capacity: '2000 KW', location: 'Sanchi, Dist. Raisen', year: 'Ongoing' },
  { title: '2 MW Ground Mounted On-Grid EPC \u2014 Love Patel', capacity: '2000 KW', location: 'Begumgunj Raisen, Dist. Raisen', year: 'Ongoing' },
  { title: '1.5 MW Ground Mounted On-Grid EPC \u2014 Spna Baghel', capacity: '1500 KW', location: 'Dabra, Dist. Gwalior', year: 'Ongoing' },
  { title: '2 MW Ground Mounted On-Grid EPC \u2014 Vishwir Singh Raghuwanshi', capacity: '2000 KW', location: 'Banskhedi, Dist. Guna', year: 'Ongoing' },
  { title: '2 MW Ground Mounted On-Grid EPC \u2014 Maa Vijasen Solar Pvt. Ltd.', capacity: '2000 KW', location: 'Berasiya, Dist. Bhopal', year: 'Ongoing' },
  { title: '2 MW Ground Mounted On-Grid EPC \u2014 Maa Shanti Solar Power Plant Pvt. Ltd.', capacity: '2000 KW', location: 'Berasiya, Dist. Bhopal', year: 'Ongoing' },
  { title: '2 MW Ground Mounted On-Grid EPC \u2014 Maa Shail Kumari Solar Energy Pvt. Ltd.', capacity: '2000 KW', location: 'Nagaon, Dist. Chhattarpur', year: 'Ongoing' },
  { title: '2 MW Ground Mounted On-Grid EPC \u2014 Sashi Parihar', capacity: '2000 KW', location: 'Rajnagar, Dist. Chhattarpur', year: 'Ongoing' },
];

export const COMPLETED_SOLAR_PROJECTS = [
  { title: '20 MW Ground Mounted On-Grid EPC', capacity: '20 MW', location: 'Guna, M.P.', year: '2024' },
  { title: '8 MW Ground Mounted On-Grid EPC', capacity: '8 MW', location: 'Chhatarpur, M.P.', year: '2023' },
  { title: '5 MW Ground Mounted On-Grid EPC', capacity: '5 MW', location: 'Bhopal, M.P.', year: '2023' },
  { title: '5 MW Ground Mounted On-Grid EPC', capacity: '5 MW', location: 'Berasiya, Bhopal, M.P.', year: '2022' },
  { title: '3.5 MW Ground Mounted On-Grid EPC', capacity: '3.5 MW', location: 'Gwalior, M.P.', year: '2022' },
  { title: '2.4 MW Ground Mounted On-Grid EPC', capacity: '2.4 MW', location: 'Raisen, M.P.', year: '2022' },
  { title: '2.4 MW Ground Mounted On-Grid EPC', capacity: '2.4 MW', location: 'Seoni, M.P.', year: '2022' },
  { title: '2.4 MW Ground Mounted On-Grid EPC', capacity: '2.4 MW', location: 'Begamganj, M.P.', year: '2021' },
  { title: '2.2 MW Ground Mounted On-Grid EPC', capacity: '2.2 MW', location: 'Rajnagar, Chhattarpur, M.P.', year: '2021' },
  { title: '2 MW Ground Mounted On-Grid EPC', capacity: '2 MW', location: 'Khawasa, M.P.', year: '2021' },
  { title: '1 MW Ground Mounted Solar Power Plant', capacity: '1 MW', location: 'Bhopal Airport', year: '2018' },
  { title: '500 KW Ground Mount Solar (On-Grid)', capacity: '500 KW', location: 'Arhedi, Bhopal, MP', year: '2022' },
  { title: '500 KW Ground Mount Solar (On-Grid)', capacity: '500 KW', location: 'Coimbatore, Tamilnadu', year: '2022' },
  { title: '300 KW Rooftop + 1200 KW Off-Grid Solar Pumps', capacity: '1500 KW', location: 'Bhopal', year: '2020' },
  { title: '200 KW Rooftop Solar \u2014 DRDO', capacity: '200 KW', location: 'Mayur Bihar DRDO, Delhi', year: '2024' },
  { title: '200 KW Rooftop Solar \u2014 Civil Hospital', capacity: '200 KW', location: 'Anupur, MP', year: '2023' },
  { title: '200 KW Rooftop Off-Grid \u2014 Govt. Hospital', capacity: '200 KW', location: 'Shivpuri, MP', year: '2019' },
  { title: '150 KW Rooftop Solar \u2014 CV Raman University', capacity: '150 KW', location: 'Bilaspur, Chhattisgarh', year: '2023' },
  { title: '50 KW Rooftop Solar (On-Grid)', capacity: '50 KW', location: 'Amjhara, Bhopal, MP', year: '2023' },
];

export const TRANSMISSION_PROJECTS = [
  { title: '765 KV Transmission Line \u2014 L&T Construction / PGCIL', capacity: '765 KV T/L', location: 'Nokha, Rajasthan', year: '2024' },
  { title: '220 KV Transmission Line \u2014 Bajaj Electrical / MPPTCL', capacity: '220 KV T/L', location: 'Petlabad', year: '2019' },
  { title: '132 KV Transmission Line \u2014 Bajaj Electrical / MPPTCL', capacity: '132 KV T/L', location: 'Bistan', year: '2018' },
  { title: '132 KV Transmission Line \u2014 L&T P&T / MPPTCL', capacity: '132 KV T/L', location: 'Rajgarh', year: '2019' },
  { title: '132 KV Pressurized Irrigation \u2014 L&T Construction / MPWRD', capacity: '132 KV T/L', location: 'Kundalia, Rajgarh', year: '2020' },
  { title: '132 KV Transmission Line \u2014 L&T Construction / NVDA', capacity: '132 KV', location: 'Astha', year: '2021' },
  { title: '132 KV Transmission Line \u2014 RS Infra / MPPTCL', capacity: '132 KV T/L', location: 'Dindori', year: '2019' },
  { title: '132 KV Traction Substation \u2014 KEC / Indian Railways', capacity: '132 KV S/S', location: 'Balaghat', year: '2020' },
  { title: '132 KV Substation \u2014 Shyam Steel / MPPTCL', capacity: '132 KV S/S', location: 'Bhopal', year: '2020' },
];

export const PROJECT_STATS = [
  { label: 'Projects Delivered', value: '100+' },
  { label: 'Years Experience', value: '7+' },
  { label: 'MW Installed', value: '50+' },
  { label: 'States Covered', value: '9' },
];
